export const sourceCountries = [
 {
  "id": 1,
  "cca2": "TN",
  "cca3": "TUN",
  "nome_comum": "Tunisia",
  "populacao": 11818618,
  "area_km2": 163610,
  "capital": "Tunis",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "República da Tunísia",
  "comum_ptBr": "Tunísia"
 },
 {
  "id": 2,
  "cca2": "AD",
  "cca3": "AND",
  "nome_comum": "Andorra",
  "populacao": 77265,
  "area_km2": 468,
  "capital": "Andorra la Vella",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "Principado de Andorra",
  "comum_ptBr": "Andorra"
 },
 {
  "id": 3,
  "cca2": "VN",
  "cca3": "VNM",
  "nome_comum": "Vietnam",
  "populacao": 97338583,
  "area_km2": 331212,
  "capital": "Hanoi",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "República Socialista do Vietname",
  "comum_ptBr": "Vietname"
 },
 {
  "id": 4,
  "cca2": "EC",
  "cca3": "ECU",
  "nome_comum": "Ecuador",
  "populacao": 17643060,
  "area_km2": 276841,
  "capital": "Quito",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República do Equador",
  "comum_ptBr": "Equador"
 },
 {
  "id": 5,
  "cca2": "PR",
  "cca3": "PRI",
  "nome_comum": "Puerto Rico",
  "populacao": 3194034,
  "area_km2": 8870,
  "capital": "San Juan",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Commonwealth of Puerto Rico",
  "comum_ptBr": "Porto Rico"
 },
 {
  "id": 6,
  "cca2": "US",
  "cca3": "USA",
  "nome_comum": "United States",
  "populacao": 329484123,
  "area_km2": 9372610,
  "capital": "Washington, D.C.",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Estados Unidos da América",
  "comum_ptBr": "Estados Unidos"
 },
 {
  "id": 7,
  "cca2": "GS",
  "cca3": "SGS",
  "nome_comum": "South Georgia",
  "populacao": 30,
  "area_km2": 3903,
  "capital": "King Edward Point",
  "regiao": "Antarctic",
  "sub_regiao": "",
  "oficial_ptBr": "Geórgia do Sul e Sandwich do Sul",
  "comum_ptBr": "Ilhas Geórgia do Sul e Sandwich do Sul"
 },
 {
  "id": 8,
  "cca2": "IL",
  "cca3": "ISR",
  "nome_comum": "Israel",
  "populacao": 9216900,
  "area_km2": 20770,
  "capital": "Jerusalem",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Estado de Israel",
  "comum_ptBr": "Israel"
 },
 {
  "id": 9,
  "cca2": "GB",
  "cca3": "GBR",
  "nome_comum": "United Kingdom",
  "populacao": 67215293,
  "area_km2": 242900,
  "capital": "London",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Reino Unido da Grã-Bretanha e Irlanda do Norte",
  "comum_ptBr": "Reino Unido"
 },
 {
  "id": 10,
  "cca2": "VG",
  "cca3": "VGB",
  "nome_comum": "British Virgin Islands",
  "populacao": 30237,
  "area_km2": 151,
  "capital": "Road Town",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Ilhas Virgens",
  "comum_ptBr": "Ilhas Virgens"
 },
 {
  "id": 11,
  "cca2": "MM",
  "cca3": "MMR",
  "nome_comum": "Myanmar",
  "populacao": 54409794,
  "area_km2": 676578,
  "capital": "Naypyidaw",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "República da União de Myanmar",
  "comum_ptBr": "Myanmar"
 },
 {
  "id": 12,
  "cca2": "PL",
  "cca3": "POL",
  "nome_comum": "Poland",
  "populacao": 37950802,
  "area_km2": 312679,
  "capital": "Warsaw",
  "regiao": "Europe",
  "sub_regiao": "Central Europe",
  "oficial_ptBr": "República da Polónia",
  "comum_ptBr": "Polónia"
 },
 {
  "id": 13,
  "cca2": "TC",
  "cca3": "TCA",
  "nome_comum": "Turks and Caicos Islands",
  "populacao": 38718,
  "area_km2": 948,
  "capital": "Cockburn Town",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Ilhas Turks e Caicos",
  "comum_ptBr": "Ilhas Turks e Caicos"
 },
 {
  "id": 14,
  "cca2": "AF",
  "cca3": "AFG",
  "nome_comum": "Afghanistan",
  "populacao": 40218234,
  "area_km2": 652230,
  "capital": "Kabul",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República Islâmica do Afeganistão",
  "comum_ptBr": "Afeganistão"
 },
 {
  "id": 15,
  "cca2": "GP",
  "cca3": "GLP",
  "nome_comum": "Guadeloupe",
  "populacao": 400132,
  "area_km2": 1628,
  "capital": "Basse-Terre",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Guadalupe",
  "comum_ptBr": "Guadalupe"
 },
 {
  "id": 16,
  "cca2": "KE",
  "cca3": "KEN",
  "nome_comum": "Kenya",
  "populacao": 53771300,
  "area_km2": 580367,
  "capital": "Nairobi",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República do Quénia",
  "comum_ptBr": "Quénia"
 },
 {
  "id": 17,
  "cca2": "AS",
  "cca3": "ASM",
  "nome_comum": "American Samoa",
  "populacao": 55197,
  "area_km2": 199,
  "capital": "Pago Pago",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Samoa americana",
  "comum_ptBr": "Samoa Americana"
 },
 {
  "id": 18,
  "cca2": "AO",
  "cca3": "AGO",
  "nome_comum": "Angola",
  "populacao": 32866268,
  "area_km2": 1246700,
  "capital": "Luanda",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República de Angola",
  "comum_ptBr": "Angola"
 },
 {
  "id": 19,
  "cca2": "BT",
  "cca3": "BTN",
  "nome_comum": "Bhutan",
  "populacao": 771612,
  "area_km2": 38394,
  "capital": "Thimphu",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "Reino do Butão",
  "comum_ptBr": "Butão"
 },
 {
  "id": 20,
  "cca2": "MT",
  "cca3": "MLT",
  "nome_comum": "Malta",
  "populacao": 525285,
  "area_km2": 316,
  "capital": "Valletta",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "República de Malta",
  "comum_ptBr": "Malta"
 },
 {
  "id": 21,
  "cca2": "JE",
  "cca3": "JEY",
  "nome_comum": "Jersey",
  "populacao": 100800,
  "area_km2": 116,
  "capital": "Saint Helier",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Bailiado de Jersey",
  "comum_ptBr": "Jersey"
 },
 {
  "id": 22,
  "cca2": "RU",
  "cca3": "RUS",
  "nome_comum": "Russia",
  "populacao": 144104080,
  "area_km2": 17098242,
  "capital": "Moscow",
  "regiao": "Europe",
  "sub_regiao": "Eastern Europe",
  "oficial_ptBr": "Federação Russa",
  "comum_ptBr": "Rússia"
 },
 {
  "id": 23,
  "cca2": "NP",
  "cca3": "NPL",
  "nome_comum": "Nepal",
  "populacao": 29136808,
  "area_km2": 147181,
  "capital": "Kathmandu",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República Democrática Federal do Nepal",
  "comum_ptBr": "Nepal"
 },
 {
  "id": 24,
  "cca2": "GW",
  "cca3": "GNB",
  "nome_comum": "Guinea-Bissau",
  "populacao": 1967998,
  "area_km2": 36125,
  "capital": "Bissau",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República da Guiné-Bissau",
  "comum_ptBr": "Guiné-Bissau"
 },
 {
  "id": 25,
  "cca2": "IQ",
  "cca3": "IRQ",
  "nome_comum": "Iraq",
  "populacao": 40222503,
  "area_km2": 438317,
  "capital": "Baghdad",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República do Iraque",
  "comum_ptBr": "Iraque"
 },
 {
  "id": 26,
  "cca2": "SD",
  "cca3": "SDN",
  "nome_comum": "Sudan",
  "populacao": 43849269,
  "area_km2": 1886068,
  "capital": "Khartoum",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "República do Sudão",
  "comum_ptBr": "Sudão"
 },
 {
  "id": 27,
  "cca2": "PF",
  "cca3": "PYF",
  "nome_comum": "French Polynesia",
  "populacao": 280904,
  "area_km2": 4167,
  "capital": "Papeetē",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Polinésia Francesa",
  "comum_ptBr": "Polinésia Francesa"
 },
 {
  "id": 28,
  "cca2": "DJ",
  "cca3": "DJI",
  "nome_comum": "Djibouti",
  "populacao": 988002,
  "area_km2": 23200,
  "capital": "Djibouti",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República do Djibouti",
  "comum_ptBr": "Djibouti"
 },
 {
  "id": 29,
  "cca2": "MZ",
  "cca3": "MOZ",
  "nome_comum": "Mozambique",
  "populacao": 31255435,
  "area_km2": 801590,
  "capital": "Maputo",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República de Moçambique",
  "comum_ptBr": "Moçambique"
 },
 {
  "id": 30,
  "cca2": "VI",
  "cca3": "VIR",
  "nome_comum": "United States Virgin Islands",
  "populacao": 106290,
  "area_km2": 347,
  "capital": "Charlotte Amalie",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Ilhas Virgens dos Estados Unidos",
  "comum_ptBr": "Ilhas Virgens dos Estados Unidos"
 },
 {
  "id": 31,
  "cca2": "AW",
  "cca3": "ABW",
  "nome_comum": "Aruba",
  "populacao": 106766,
  "area_km2": 180,
  "capital": "Oranjestad",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Aruba",
  "comum_ptBr": "Aruba"
 },
 {
  "id": 32,
  "cca2": "SH",
  "cca3": "SHN",
  "nome_comum": "Saint Helena, Ascension and Tristan da Cunha",
  "populacao": 53192,
  "area_km2": 394,
  "capital": "Jamestown",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "Santa Helena, Ascensão e Tristão da Cunha",
  "comum_ptBr": "Santa Helena, Ascensão e Tristão da Cunha"
 },
 {
  "id": 33,
  "cca2": "ZA",
  "cca3": "ZAF",
  "nome_comum": "South Africa",
  "populacao": 59308690,
  "area_km2": 1221037,
  "capital": "Pretoria",
  "regiao": "Africa",
  "sub_regiao": "Southern Africa",
  "oficial_ptBr": "República da África do Sul",
  "comum_ptBr": "África do Sul"
 },
 {
  "id": 34,
  "cca2": "LI",
  "cca3": "LIE",
  "nome_comum": "Liechtenstein",
  "populacao": 38137,
  "area_km2": 160,
  "capital": "Vaduz",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "Principado de Liechtenstein",
  "comum_ptBr": "Liechtenstein"
 },
 {
  "id": 35,
  "cca2": "ST",
  "cca3": "STP",
  "nome_comum": "São Tomé and Príncipe",
  "populacao": 219161,
  "area_km2": 964,
  "capital": "São Tomé",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República Democrática de São Tomé e Príncipe",
  "comum_ptBr": "São Tomé e Príncipe"
 },
 {
  "id": 36,
  "cca2": "BI",
  "cca3": "BDI",
  "nome_comum": "Burundi",
  "populacao": 11890781,
  "area_km2": 27834,
  "capital": "Gitega",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República do Burundi",
  "comum_ptBr": "Burundi"
 },
 {
  "id": 37,
  "cca2": "RW",
  "cca3": "RWA",
  "nome_comum": "Rwanda",
  "populacao": 12952209,
  "area_km2": 26338,
  "capital": "Kigali",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República do Ruanda",
  "comum_ptBr": "Ruanda"
 },
 {
  "id": 38,
  "cca2": "BE",
  "cca3": "BEL",
  "nome_comum": "Belgium",
  "populacao": 11555997,
  "area_km2": 30528,
  "capital": "Brussels",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "Reino da Bélgica",
  "comum_ptBr": "Bélgica"
 },
 {
  "id": 39,
  "cca2": "GU",
  "cca3": "GUM",
  "nome_comum": "Guam",
  "populacao": 168783,
  "area_km2": 549,
  "capital": "Hagåtña",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "Guam",
  "comum_ptBr": "Guam"
 },
 {
  "id": 40,
  "cca2": "JO",
  "cca3": "JOR",
  "nome_comum": "Jordan",
  "populacao": 10203140,
  "area_km2": 89342,
  "capital": "Amman",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Reino Hachemita da Jordânia",
  "comum_ptBr": "Jordânia"
 },
 {
  "id": 41,
  "cca2": "MP",
  "cca3": "MNP",
  "nome_comum": "Northern Mariana Islands",
  "populacao": 57557,
  "area_km2": 464,
  "capital": "Saipan",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "Comunidade das Ilhas Marianas do Norte",
  "comum_ptBr": "Marianas Setentrionais"
 },
 {
  "id": 42,
  "cca2": "GQ",
  "cca3": "GNQ",
  "nome_comum": "Equatorial Guinea",
  "populacao": 1402985,
  "area_km2": 28051,
  "capital": "Malabo",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República da Guiné Equatorial",
  "comum_ptBr": "Guiné Equatorial"
 },
 {
  "id": 43,
  "cca2": "MH",
  "cca3": "MHL",
  "nome_comum": "Marshall Islands",
  "populacao": 59194,
  "area_km2": 181,
  "capital": "Majuro",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "República das Ilhas Marshall",
  "comum_ptBr": "Ilhas Marshall"
 },
 {
  "id": 44,
  "cca2": "NU",
  "cca3": "NIU",
  "nome_comum": "Niue",
  "populacao": 1470,
  "area_km2": 260,
  "capital": "Alofi",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Niue",
  "comum_ptBr": "Niue"
 },
 {
  "id": 45,
  "cca2": "ES",
  "cca3": "ESP",
  "nome_comum": "Spain",
  "populacao": 47351567,
  "area_km2": 505992,
  "capital": "Madrid",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "Reino de Espanha",
  "comum_ptBr": "Espanha"
 },
 {
  "id": 46,
  "cca2": "KG",
  "cca3": "KGZ",
  "nome_comum": "Kyrgyzstan",
  "populacao": 6591600,
  "area_km2": 199951,
  "capital": "Bishkek",
  "regiao": "Asia",
  "sub_regiao": "Central Asia",
  "oficial_ptBr": "República do Quirguistão",
  "comum_ptBr": "Quirguistão"
 },
 {
  "id": 47,
  "cca2": "BV",
  "cca3": "BVT",
  "nome_comum": "Bouvet Island",
  "populacao": 0,
  "area_km2": 49,
  "regiao": "Antarctic",
  "sub_regiao": "",
  "oficial_ptBr": "Ilha Bouvet",
  "comum_ptBr": "Ilha Bouvet"
 },
 {
  "id": 48,
  "cca2": "MR",
  "cca3": "MRT",
  "nome_comum": "Mauritania",
  "populacao": 4649660,
  "area_km2": 1030700,
  "capital": "Nouakchott",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República Islâmica da Mauritânia",
  "comum_ptBr": "Mauritânia"
 },
 {
  "id": 49,
  "cca2": "WS",
  "cca3": "WSM",
  "nome_comum": "Samoa",
  "populacao": 198410,
  "area_km2": 2842,
  "capital": "Apia",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Estado Independente de Samoa",
  "comum_ptBr": "Samoa"
 },
 {
  "id": 50,
  "cca2": "MW",
  "cca3": "MWI",
  "nome_comum": "Malawi",
  "populacao": 19129955,
  "area_km2": 118484,
  "capital": "Lilongwe",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República do Malawi",
  "comum_ptBr": "Malawi"
 },
 {
  "id": 51,
  "cca2": "PA",
  "cca3": "PAN",
  "nome_comum": "Panama",
  "populacao": 4314768,
  "area_km2": 75417,
  "capital": "Panama City",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "República do Panamá",
  "comum_ptBr": "Panamá"
 },
 {
  "id": 52,
  "cca2": "TH",
  "cca3": "THA",
  "nome_comum": "Thailand",
  "populacao": 69799978,
  "area_km2": 513120,
  "capital": "Bangkok",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "Reino da Tailândia",
  "comum_ptBr": "Tailândia"
 },
 {
  "id": 53,
  "cca2": "TR",
  "cca3": "TUR",
  "nome_comum": "Turkey",
  "populacao": 84339067,
  "area_km2": 783562,
  "capital": "Ankara",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República da Turquia",
  "comum_ptBr": "Turquia"
 },
 {
  "id": 54,
  "cca2": "PH",
  "cca3": "PHL",
  "nome_comum": "Philippines",
  "populacao": 109581085,
  "area_km2": 342353,
  "capital": "Manila",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "República das Filipinas",
  "comum_ptBr": "Filipinas"
 },
 {
  "id": 55,
  "cca2": "PN",
  "cca3": "PCN",
  "nome_comum": "Pitcairn Islands",
  "populacao": 56,
  "area_km2": 47,
  "capital": "Adamstown",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Pitcairn grupo de ilhas",
  "comum_ptBr": "Ilhas Pitcairn"
 },
 {
  "id": 56,
  "cca2": "SI",
  "cca3": "SVN",
  "nome_comum": "Slovenia",
  "populacao": 2100126,
  "area_km2": 20273,
  "capital": "Ljubljana",
  "regiao": "Europe",
  "sub_regiao": "Central Europe",
  "oficial_ptBr": "República da Eslovénia",
  "comum_ptBr": "Eslovénia"
 },
 {
  "id": 57,
  "cca2": "AE",
  "cca3": "ARE",
  "nome_comum": "United Arab Emirates",
  "populacao": 9890400,
  "area_km2": 83600,
  "capital": "Abu Dhabi",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Emirados Árabes Unidos",
  "comum_ptBr": "Emirados Árabes Unidos"
 },
 {
  "id": 58,
  "cca2": "GE",
  "cca3": "GEO",
  "nome_comum": "Georgia",
  "populacao": 3714000,
  "area_km2": 69700,
  "capital": "Tbilisi",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Georgia",
  "comum_ptBr": "Geórgia"
 },
 {
  "id": 59,
  "cca2": "GR",
  "cca3": "GRC",
  "nome_comum": "Greece",
  "populacao": 10715549,
  "area_km2": 131990,
  "capital": "Athens",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "República Helénica",
  "comum_ptBr": "Grécia"
 },
 {
  "id": 60,
  "cca2": "AM",
  "cca3": "ARM",
  "nome_comum": "Armenia",
  "populacao": 2963234,
  "area_km2": 29743,
  "capital": "Yerevan",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República da Arménia",
  "comum_ptBr": "Arménia"
 },
 {
  "id": 61,
  "cca2": "CC",
  "cca3": "CCK",
  "nome_comum": "Cocos (Keeling) Islands",
  "populacao": 544,
  "area_km2": 14,
  "capital": "West Island",
  "regiao": "Oceania",
  "sub_regiao": "Australia and New Zealand",
  "oficial_ptBr": "Território dos Cocos (Keeling)",
  "comum_ptBr": "Ilhas Cocos (Keeling)"
 },
 {
  "id": 62,
  "cca2": "CR",
  "cca3": "CRI",
  "nome_comum": "Costa Rica",
  "populacao": 5094114,
  "area_km2": 51100,
  "capital": "San José",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "República da Costa Rica",
  "comum_ptBr": "Costa Rica"
 },
 {
  "id": 63,
  "cca2": "KI",
  "cca3": "KIR",
  "nome_comum": "Kiribati",
  "populacao": 119446,
  "area_km2": 811,
  "capital": "South Tarawa",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "Independente e soberano República de Kiribati",
  "comum_ptBr": "Kiribati"
 },
 {
  "id": 64,
  "cca2": "TZ",
  "cca3": "TZA",
  "nome_comum": "Tanzania",
  "populacao": 59734213,
  "area_km2": 945087,
  "capital": "Dodoma",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República Unida da Tanzânia",
  "comum_ptBr": "Tanzânia"
 },
 {
  "id": 65,
  "cca2": "SS",
  "cca3": "SSD",
  "nome_comum": "South Sudan",
  "populacao": 11193729,
  "area_km2": 619745,
  "capital": "Juba",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República do Sudão do Sul",
  "comum_ptBr": "Sudão do Sul"
 },
 {
  "id": 66,
  "cca2": "IR",
  "cca3": "IRN",
  "nome_comum": "Iran",
  "populacao": 83992953,
  "area_km2": 1648195,
  "capital": "Tehran",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República Islâmica do Irã",
  "comum_ptBr": "Irão"
 },
 {
  "id": 67,
  "cca2": "FM",
  "cca3": "FSM",
  "nome_comum": "Micronesia",
  "populacao": 115021,
  "area_km2": 702,
  "capital": "Palikir",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "Estados Federados da Micronésia",
  "comum_ptBr": "Micronésia"
 },
 {
  "id": 68,
  "cca2": "SJ",
  "cca3": "SJM",
  "nome_comum": "Svalbard and Jan Mayen",
  "populacao": 2562,
  "area_km2": 61399,
  "capital": "Longyearbyen",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Svalbard og Jan Mayen",
  "comum_ptBr": "Ilhas Svalbard e Jan Mayen"
 },
 {
  "id": 69,
  "cca2": "MN",
  "cca3": "MNG",
  "nome_comum": "Mongolia",
  "populacao": 3278292,
  "area_km2": 1564110,
  "capital": "Ulan Bator",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "Mongólia",
  "comum_ptBr": "Mongólia"
 },
 {
  "id": 70,
  "cca2": "MD",
  "cca3": "MDA",
  "nome_comum": "Moldova",
  "populacao": 2617820,
  "area_km2": 33846,
  "capital": "Chișinău",
  "regiao": "Europe",
  "sub_regiao": "Eastern Europe",
  "oficial_ptBr": "República da Moldávia",
  "comum_ptBr": "Moldávia"
 },
 {
  "id": 71,
  "cca2": "NZ",
  "cca3": "NZL",
  "nome_comum": "New Zealand",
  "populacao": 5084300,
  "area_km2": 270467,
  "capital": "Wellington",
  "regiao": "Oceania",
  "sub_regiao": "Australia and New Zealand",
  "oficial_ptBr": "nova Zelândia",
  "comum_ptBr": "Nova Zelândia"
 },
 {
  "id": 72,
  "cca2": "SZ",
  "cca3": "SWZ",
  "nome_comum": "Eswatini",
  "populacao": 1160164,
  "area_km2": 17364,
  "capital": "Mbabane",
  "regiao": "Africa",
  "sub_regiao": "Southern Africa",
  "oficial_ptBr": "Reino de eSwatini",
  "comum_ptBr": "Suazilândia"
 },
 {
  "id": 73,
  "cca2": "SO",
  "cca3": "SOM",
  "nome_comum": "Somalia",
  "populacao": 15893219,
  "area_km2": 637657,
  "capital": "Mogadishu",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República Federal da Somália",
  "comum_ptBr": "Somália"
 },
 {
  "id": 74,
  "cca2": "LC",
  "cca3": "LCA",
  "nome_comum": "Saint Lucia",
  "populacao": 183629,
  "area_km2": 616,
  "capital": "Castries",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Santa Lúcia",
  "comum_ptBr": "Santa Lúcia"
 },
 {
  "id": 75,
  "cca2": "GY",
  "cca3": "GUY",
  "nome_comum": "Guyana",
  "populacao": 786559,
  "area_km2": 214969,
  "capital": "Georgetown",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "Co -operative República da Guiana",
  "comum_ptBr": "Guiana"
 },
 {
  "id": 76,
  "cca2": "IM",
  "cca3": "IMN",
  "nome_comum": "Isle of Man",
  "populacao": 85032,
  "area_km2": 572,
  "capital": "Douglas",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Isle of Man",
  "comum_ptBr": "Ilha de Man"
 },
 {
  "id": 77,
  "cca2": "FO",
  "cca3": "FRO",
  "nome_comum": "Faroe Islands",
  "populacao": 48865,
  "area_km2": 1393,
  "capital": "Tórshavn",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Ilhas Faroe",
  "comum_ptBr": "Ilhas Faroé"
 },
 {
  "id": 78,
  "cca2": "BL",
  "cca3": "BLM",
  "nome_comum": "Saint Barthélemy",
  "populacao": 4255,
  "area_km2": 21,
  "capital": "Gustavia",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Coletividade de Saint Barthélemy",
  "comum_ptBr": "São Bartolomeu"
 },
 {
  "id": 79,
  "cca2": "WF",
  "cca3": "WLF",
  "nome_comum": "Wallis and Futuna",
  "populacao": 11750,
  "area_km2": 142,
  "capital": "Mata-Utu",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Território das Ilhas Wallis e Futuna",
  "comum_ptBr": "Wallis e Futuna"
 },
 {
  "id": 80,
  "cca2": "IN",
  "cca3": "IND",
  "nome_comum": "India",
  "populacao": 1380004385,
  "area_km2": 3287590,
  "capital": "New Delhi",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República da Índia",
  "comum_ptBr": "Índia"
 },
 {
  "id": 81,
  "cca2": "NE",
  "cca3": "NER",
  "nome_comum": "Niger",
  "populacao": 24206636,
  "area_km2": 1267000,
  "capital": "Niamey",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República do Níger",
  "comum_ptBr": "Níger"
 },
 {
  "id": 82,
  "cca2": "SX",
  "cca3": "SXM",
  "nome_comum": "Sint Maarten",
  "populacao": 40812,
  "area_km2": 34,
  "capital": "Philipsburg",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Sint Maarten",
  "comum_ptBr": "São Martinho"
 },
 {
  "id": 83,
  "cca2": "CD",
  "cca3": "COD",
  "nome_comum": "DR Congo",
  "populacao": 108407721,
  "area_km2": 2344858,
  "capital": "Kinshasa",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República Democrática do Congo",
  "comum_ptBr": "República Democrática do Congo"
 },
 {
  "id": 84,
  "cca2": "CG",
  "cca3": "COG",
  "nome_comum": "Republic of the Congo",
  "populacao": 5657000,
  "area_km2": 342000,
  "capital": "Brazzaville",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República do Congo",
  "comum_ptBr": "Congo"
 },
 {
  "id": 85,
  "cca2": "KR",
  "cca3": "KOR",
  "nome_comum": "South Korea",
  "populacao": 51780579,
  "area_km2": 100210,
  "capital": "Seoul",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "República da Coreia",
  "comum_ptBr": "Coreia do Sul"
 },
 {
  "id": 86,
  "cca2": "CI",
  "cca3": "CIV",
  "nome_comum": "Ivory Coast",
  "populacao": 26378275,
  "area_km2": 322463,
  "capital": "Yamoussoukro",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República da Côte d'Ivoire",
  "comum_ptBr": "Costa do Marfim"
 },
 {
  "id": 87,
  "cca2": "MV",
  "cca3": "MDV",
  "nome_comum": "Maldives",
  "populacao": 540542,
  "area_km2": 300,
  "capital": "Malé",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República das Maldivas",
  "comum_ptBr": "Maldivas"
 },
 {
  "id": 88,
  "cca2": "RS",
  "cca3": "SRB",
  "nome_comum": "Serbia",
  "populacao": 6908224,
  "area_km2": 88361,
  "capital": "Belgrade",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "República da Sérvia",
  "comum_ptBr": "Sérvia"
 },
 {
  "id": 89,
  "cca2": "ML",
  "cca3": "MLI",
  "nome_comum": "Mali",
  "populacao": 20250834,
  "area_km2": 1240192,
  "capital": "Bamako",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República do Mali",
  "comum_ptBr": "Mali"
 },
 {
  "id": 90,
  "cca2": "DZ",
  "cca3": "DZA",
  "nome_comum": "Algeria",
  "populacao": 44700000,
  "area_km2": 2381741,
  "capital": "Algiers",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "República Argelina Democrática e Popular",
  "comum_ptBr": "Argélia"
 },
 {
  "id": 91,
  "cca2": "LA",
  "cca3": "LAO",
  "nome_comum": "Laos",
  "populacao": 7275556,
  "area_km2": 236800,
  "capital": "Vientiane",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "Laos, República Democrática",
  "comum_ptBr": "Laos"
 },
 {
  "id": 92,
  "cca2": "CM",
  "cca3": "CMR",
  "nome_comum": "Cameroon",
  "populacao": 26545864,
  "area_km2": 475442,
  "capital": "Yaoundé",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República dos Camarões",
  "comum_ptBr": "Camarões"
 },
 {
  "id": 93,
  "cca2": "FI",
  "cca3": "FIN",
  "nome_comum": "Finland",
  "populacao": 5530719,
  "area_km2": 338424,
  "capital": "Helsinki",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "República da Finlândia",
  "comum_ptBr": "Finlândia"
 },
 {
  "id": 94,
  "cca2": "ZW",
  "cca3": "ZWE",
  "nome_comum": "Zimbabwe",
  "populacao": 14862927,
  "area_km2": 390757,
  "capital": "Harare",
  "regiao": "Africa",
  "sub_regiao": "Southern Africa",
  "oficial_ptBr": "República do Zimbabwe",
  "comum_ptBr": "Zimbabwe"
 },
 {
  "id": 95,
  "cca2": "MS",
  "cca3": "MSR",
  "nome_comum": "Montserrat",
  "populacao": 4922,
  "area_km2": 102,
  "capital": "Plymouth",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Montserrat",
  "comum_ptBr": "Montserrat"
 },
 {
  "id": 96,
  "cca2": "BO",
  "cca3": "BOL",
  "nome_comum": "Bolivia",
  "populacao": 11673029,
  "area_km2": 1098581,
  "capital": "Sucre",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "Estado Plurinacional da Bolívia",
  "comum_ptBr": "Bolívia"
 },
 {
  "id": 97,
  "cca2": "LS",
  "cca3": "LSO",
  "nome_comum": "Lesotho",
  "populacao": 2142252,
  "area_km2": 30355,
  "capital": "Maseru",
  "regiao": "Africa",
  "sub_regiao": "Southern Africa",
  "oficial_ptBr": "Reino do Lesoto",
  "comum_ptBr": "Lesoto"
 },
 {
  "id": 98,
  "cca2": "HU",
  "cca3": "HUN",
  "nome_comum": "Hungary",
  "populacao": 9749763,
  "area_km2": 93028,
  "capital": "Budapest",
  "regiao": "Europe",
  "sub_regiao": "Central Europe",
  "oficial_ptBr": "Hungria",
  "comum_ptBr": "Hungria"
 },
 {
  "id": 99,
  "cca2": "TM",
  "cca3": "TKM",
  "nome_comum": "Turkmenistan",
  "populacao": 6031187,
  "area_km2": 488100,
  "capital": "Ashgabat",
  "regiao": "Asia",
  "sub_regiao": "Central Asia",
  "oficial_ptBr": "Turcomenistão",
  "comum_ptBr": "Turquemenistão"
 },
 {
  "id": 100,
  "cca2": "NO",
  "cca3": "NOR",
  "nome_comum": "Norway",
  "populacao": 5379475,
  "area_km2": 323802,
  "capital": "Oslo",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Reino da Noruega",
  "comum_ptBr": "Noruega"
 },
 {
  "id": 101,
  "cca2": "PE",
  "cca3": "PER",
  "nome_comum": "Peru",
  "populacao": 32971846,
  "area_km2": 1285216,
  "capital": "Lima",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República do Peru",
  "comum_ptBr": "Perú"
 },
 {
  "id": 102,
  "cca2": "CU",
  "cca3": "CUB",
  "nome_comum": "Cuba",
  "populacao": 11326616,
  "area_km2": 109884,
  "capital": "Havana",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "República de Cuba",
  "comum_ptBr": "Cuba"
 },
 {
  "id": 103,
  "cca2": "LT",
  "cca3": "LTU",
  "nome_comum": "Lithuania",
  "populacao": 2794700,
  "area_km2": 65300,
  "capital": "Vilnius",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "República da Lituânia",
  "comum_ptBr": "Lituânia"
 },
 {
  "id": 104,
  "cca2": "KN",
  "cca3": "KNA",
  "nome_comum": "Saint Kitts and Nevis",
  "populacao": 53192,
  "area_km2": 261,
  "capital": "Basseterre",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Federação de São Cristóvão e Nevis",
  "comum_ptBr": "São Cristóvão e Nevis"
 },
 {
  "id": 105,
  "cca2": "GG",
  "cca3": "GGY",
  "nome_comum": "Guernsey",
  "populacao": 62999,
  "area_km2": 78,
  "capital": "St. Peter Port",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Bailiado de Guernsey",
  "comum_ptBr": "Guernsey"
 },
 {
  "id": 106,
  "cca2": "MU",
  "cca3": "MUS",
  "nome_comum": "Mauritius",
  "populacao": 1265740,
  "area_km2": 2040,
  "capital": "Port Louis",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República das Maurícias",
  "comum_ptBr": "Maurício"
 },
 {
  "id": 107,
  "cca2": "SA",
  "cca3": "SAU",
  "nome_comum": "Saudi Arabia",
  "populacao": 34813867,
  "area_km2": 2149690,
  "capital": "Riyadh",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Reino da Arábia Saudita",
  "comum_ptBr": "Arábia Saudita"
 },
 {
  "id": 108,
  "cca2": "CW",
  "cca3": "CUW",
  "nome_comum": "Curaçao",
  "populacao": 155014,
  "area_km2": 444,
  "capital": "Willemstad",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "País de Curaçao",
  "comum_ptBr": "ilha da Curação"
 },
 {
  "id": 109,
  "cca2": "BJ",
  "cca3": "BEN",
  "nome_comum": "Benin",
  "populacao": 12123198,
  "area_km2": 112622,
  "capital": "Porto-Novo",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República do Benin",
  "comum_ptBr": "Benin"
 },
 {
  "id": 110,
  "cca2": "SK",
  "cca3": "SVK",
  "nome_comum": "Slovakia",
  "populacao": 5458827,
  "area_km2": 49037,
  "capital": "Bratislava",
  "regiao": "Europe",
  "sub_regiao": "Central Europe",
  "oficial_ptBr": "República Eslovaca",
  "comum_ptBr": "Eslováquia"
 },
 {
  "id": 111,
  "cca2": "IO",
  "cca3": "IOT",
  "nome_comum": "British Indian Ocean Territory",
  "populacao": 3000,
  "area_km2": 60,
  "capital": "Diego Garcia",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "British Indian Ocean Territory",
  "comum_ptBr": "Território Britânico do Oceano Índico"
 },
 {
  "id": 112,
  "cca2": "TV",
  "cca3": "TUV",
  "nome_comum": "Tuvalu",
  "populacao": 11792,
  "area_km2": 26,
  "capital": "Funafuti",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Tuvalu",
  "comum_ptBr": "Tuvalu"
 },
 {
  "id": 113,
  "cca2": "GL",
  "cca3": "GRL",
  "nome_comum": "Greenland",
  "populacao": 56367,
  "area_km2": 2166086,
  "capital": "Nuuk",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Groenlândia",
  "comum_ptBr": "Gronelândia"
 },
 {
  "id": 114,
  "cca2": "CV",
  "cca3": "CPV",
  "nome_comum": "Cape Verde",
  "populacao": 555988,
  "area_km2": 4033,
  "capital": "Praia",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República de Cabo Verde",
  "comum_ptBr": "Cabo Verde"
 },
 {
  "id": 115,
  "cca2": "UZ",
  "cca3": "UZB",
  "nome_comum": "Uzbekistan",
  "populacao": 34232050,
  "area_km2": 447400,
  "capital": "Tashkent",
  "regiao": "Asia",
  "sub_regiao": "Central Asia",
  "oficial_ptBr": "República do Usbequistão",
  "comum_ptBr": "Uzbequistão"
 },
 {
  "id": 116,
  "cca2": "SE",
  "cca3": "SWE",
  "nome_comum": "Sweden",
  "populacao": 10353442,
  "area_km2": 450295,
  "capital": "Stockholm",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Reino da Suécia",
  "comum_ptBr": "Suécia"
 },
 {
  "id": 117,
  "cca2": "BD",
  "cca3": "BGD",
  "nome_comum": "Bangladesh",
  "populacao": 164689383,
  "area_km2": 147570,
  "capital": "Dhaka",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República Popular do Bangladesh",
  "comum_ptBr": "Bangladesh"
 },
 {
  "id": 118,
  "cca2": "TW",
  "cca3": "TWN",
  "nome_comum": "Taiwan",
  "populacao": 23503349,
  "area_km2": 36193,
  "capital": "Taipei",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "República da China",
  "comum_ptBr": "Ilha Formosa"
 },
 {
  "id": 119,
  "cca2": "IT",
  "cca3": "ITA",
  "nome_comum": "Italy",
  "populacao": 59554023,
  "area_km2": 301336,
  "capital": "Rome",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "República Italiana",
  "comum_ptBr": "Itália"
 },
 {
  "id": 120,
  "cca2": "TD",
  "cca3": "TCD",
  "nome_comum": "Chad",
  "populacao": 16425859,
  "area_km2": 1284000,
  "capital": "N'Djamena",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República do Chade",
  "comum_ptBr": "Chade"
 },
 {
  "id": 121,
  "cca2": "SY",
  "cca3": "SYR",
  "nome_comum": "Syria",
  "populacao": 17500657,
  "area_km2": 185180,
  "capital": "Damascus",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República Árabe Síria",
  "comum_ptBr": "Síria"
 },
 {
  "id": 122,
  "cca2": "CL",
  "cca3": "CHL",
  "nome_comum": "Chile",
  "populacao": 19116209,
  "area_km2": 756102,
  "capital": "Santiago",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República do Chile",
  "comum_ptBr": "Chile"
 },
 {
  "id": 123,
  "cca2": "SN",
  "cca3": "SEN",
  "nome_comum": "Senegal",
  "populacao": 16743930,
  "area_km2": 196722,
  "capital": "Dakar",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República do Senegal",
  "comum_ptBr": "Senegal"
 },
 {
  "id": 124,
  "cca2": "BF",
  "cca3": "BFA",
  "nome_comum": "Burkina Faso",
  "populacao": 20903278,
  "area_km2": 272967,
  "capital": "Ouagadougou",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "Burkina Faso",
  "comum_ptBr": "Burkina Faso"
 },
 {
  "id": 125,
  "cca2": "RO",
  "cca3": "ROU",
  "nome_comum": "Romania",
  "populacao": 19286123,
  "area_km2": 238391,
  "capital": "Bucharest",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "Romênia",
  "comum_ptBr": "Roménia"
 },
 {
  "id": 126,
  "cca2": "BR",
  "cca3": "BRA",
  "nome_comum": "Brazil",
  "populacao": 212559409,
  "area_km2": 8515767,
  "capital": "Brasília",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República Federativa do Brasil",
  "comum_ptBr": "Brasil"
 },
 {
  "id": 127,
  "cca2": "YT",
  "cca3": "MYT",
  "nome_comum": "Mayotte",
  "populacao": 226915,
  "area_km2": 374,
  "capital": "Mamoudzou",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "Departamento de Mayotte",
  "comum_ptBr": "Mayotte"
 },
 {
  "id": 128,
  "cca2": "DM",
  "cca3": "DMA",
  "nome_comum": "Dominica",
  "populacao": 71991,
  "area_km2": 751,
  "capital": "Roseau",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Comunidade da Dominica",
  "comum_ptBr": "Dominica"
 },
 {
  "id": 129,
  "cca2": "EE",
  "cca3": "EST",
  "nome_comum": "Estonia",
  "populacao": 1331057,
  "area_km2": 45227,
  "capital": "Tallinn",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "República da Estónia",
  "comum_ptBr": "Estónia"
 },
 {
  "id": 130,
  "cca2": "TG",
  "cca3": "TGO",
  "nome_comum": "Togo",
  "populacao": 8278737,
  "area_km2": 56785,
  "capital": "Lomé",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República do Togo",
  "comum_ptBr": "Togo"
 },
 {
  "id": 131,
  "cca2": "KH",
  "cca3": "KHM",
  "nome_comum": "Cambodia",
  "populacao": 16718971,
  "area_km2": 181035,
  "capital": "Phnom Penh",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "Reino do Camboja",
  "comum_ptBr": "Camboja"
 },
 {
  "id": 132,
  "cca2": "DO",
  "cca3": "DOM",
  "nome_comum": "Dominican Republic",
  "populacao": 10847904,
  "area_km2": 48671,
  "capital": "Santo Domingo",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "República Dominicana",
  "comum_ptBr": "República Dominicana"
 },
 {
  "id": 133,
  "cca2": "NF",
  "cca3": "NFK",
  "nome_comum": "Norfolk Island",
  "populacao": 2302,
  "area_km2": 36,
  "capital": "Kingston",
  "regiao": "Oceania",
  "sub_regiao": "Australia and New Zealand",
  "oficial_ptBr": "Território da Ilha Norfolk",
  "comum_ptBr": "Ilha Norfolk"
 },
 {
  "id": 134,
  "cca2": "CA",
  "cca3": "CAN",
  "nome_comum": "Canada",
  "populacao": 38005238,
  "area_km2": 9984670,
  "capital": "Ottawa",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Canadá",
  "comum_ptBr": "Canadá"
 },
 {
  "id": 135,
  "cca2": "TF",
  "cca3": "ATF",
  "nome_comum": "French Southern and Antarctic Lands",
  "populacao": 400,
  "area_km2": 7747,
  "capital": "Port-aux-Français",
  "regiao": "Antarctic",
  "sub_regiao": "",
  "oficial_ptBr": "Território do Sul e Antártica Francesa",
  "comum_ptBr": "Terras Austrais e Antárticas Francesas"
 },
 {
  "id": 136,
  "cca2": "PY",
  "cca3": "PRY",
  "nome_comum": "Paraguay",
  "populacao": 7132530,
  "area_km2": 406752,
  "capital": "Asunción",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República do Paraguai",
  "comum_ptBr": "Paraguai"
 },
 {
  "id": 137,
  "cca2": "KZ",
  "cca3": "KAZ",
  "nome_comum": "Kazakhstan",
  "populacao": 18754440,
  "area_km2": 2724900,
  "capital": "Astana",
  "regiao": "Asia",
  "sub_regiao": "Central Asia",
  "oficial_ptBr": "República do Cazaquistão",
  "comum_ptBr": "Cazaquistão"
 },
 {
  "id": 138,
  "cca2": "ID",
  "cca3": "IDN",
  "nome_comum": "Indonesia",
  "populacao": 273523621,
  "area_km2": 1904569,
  "capital": "Jakarta",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "República da Indonésia",
  "comum_ptBr": "Indonésia"
 },
 {
  "id": 139,
  "cca2": "LU",
  "cca3": "LUX",
  "nome_comum": "Luxembourg",
  "populacao": 632275,
  "area_km2": 2586,
  "capital": "Luxembourg",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "Grão-Ducado do Luxemburgo",
  "comum_ptBr": "Luxemburgo"
 },
 {
  "id": 140,
  "cca2": "EH",
  "cca3": "ESH",
  "nome_comum": "Western Sahara",
  "populacao": 510713,
  "area_km2": 266000,
  "capital": "El Aaiún",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "República Árabe Saharaui Democrática",
  "comum_ptBr": "Saara Ocidental"
 },
 {
  "id": 141,
  "cca2": "KM",
  "cca3": "COM",
  "nome_comum": "Comoros",
  "populacao": 869595,
  "area_km2": 1862,
  "capital": "Moroni",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "União das Comores",
  "comum_ptBr": "Comores"
 },
 {
  "id": 142,
  "cca2": "AG",
  "cca3": "ATG",
  "nome_comum": "Antigua and Barbuda",
  "populacao": 97928,
  "area_km2": 442,
  "capital": "Saint John's",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Antigua e Barbuda",
  "comum_ptBr": "Antígua e Barbuda"
 },
 {
  "id": 143,
  "cca2": "BG",
  "cca3": "BGR",
  "nome_comum": "Bulgaria",
  "populacao": 6927288,
  "area_km2": 110879,
  "capital": "Sofia",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "República da Bulgária",
  "comum_ptBr": "Bulgária"
 },
 {
  "id": 144,
  "cca2": "FK",
  "cca3": "FLK",
  "nome_comum": "Falkland Islands",
  "populacao": 2563,
  "area_km2": 12173,
  "capital": "Stanley",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "Ilhas Malvinas",
  "comum_ptBr": "Ilhas Malvinas"
 },
 {
  "id": 145,
  "cca2": "HN",
  "cca3": "HND",
  "nome_comum": "Honduras",
  "populacao": 9904608,
  "area_km2": 112492,
  "capital": "Tegucigalpa",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "República de Honduras",
  "comum_ptBr": "Honduras"
 },
 {
  "id": 146,
  "cca2": "UY",
  "cca3": "URY",
  "nome_comum": "Uruguay",
  "populacao": 3473727,
  "area_km2": 181034,
  "capital": "Montevideo",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República Oriental do Uruguai",
  "comum_ptBr": "Uruguai"
 },
 {
  "id": 147,
  "cca2": "PM",
  "cca3": "SPM",
  "nome_comum": "Saint Pierre and Miquelon",
  "populacao": 6069,
  "area_km2": 242,
  "capital": "Saint-Pierre",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Saint Pierre e Miquelon",
  "comum_ptBr": "Saint-Pierre e Miquelon"
 },
 {
  "id": 148,
  "cca2": "ET",
  "cca3": "ETH",
  "nome_comum": "Ethiopia",
  "populacao": 114963583,
  "area_km2": 1104300,
  "capital": "Addis Ababa",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República Federal Democrática da Etiópia",
  "comum_ptBr": "Etiópia"
 },
 {
  "id": 149,
  "cca2": "TJ",
  "cca3": "TJK",
  "nome_comum": "Tajikistan",
  "populacao": 9537642,
  "area_km2": 143100,
  "capital": "Dushanbe",
  "regiao": "Asia",
  "sub_regiao": "Central Asia",
  "oficial_ptBr": "República do Tajiquistão",
  "comum_ptBr": "Tajiquistão"
 },
 {
  "id": 150,
  "cca2": "TK",
  "cca3": "TKL",
  "nome_comum": "Tokelau",
  "populacao": 1411,
  "area_km2": 12,
  "capital": "Fakaofo",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Tokelau",
  "comum_ptBr": "Tokelau"
 },
 {
  "id": 151,
  "cca2": "BW",
  "cca3": "BWA",
  "nome_comum": "Botswana",
  "populacao": 2351625,
  "area_km2": 582000,
  "capital": "Gaborone",
  "regiao": "Africa",
  "sub_regiao": "Southern Africa",
  "oficial_ptBr": "República do Botswana",
  "comum_ptBr": "Botswana"
 },
 {
  "id": 152,
  "cca2": "AL",
  "cca3": "ALB",
  "nome_comum": "Albania",
  "populacao": 2837743,
  "area_km2": 28748,
  "capital": "Tirana",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "República da Albânia",
  "comum_ptBr": "Albânia"
 },
 {
  "id": 153,
  "cca2": "NG",
  "cca3": "NGA",
  "nome_comum": "Nigeria",
  "populacao": 206139587,
  "area_km2": 923768,
  "capital": "Abuja",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República Federal da Nigéria",
  "comum_ptBr": "Nigéria"
 },
 {
  "id": 154,
  "cca2": "GM",
  "cca3": "GMB",
  "nome_comum": "Gambia",
  "populacao": 2416664,
  "area_km2": 10689,
  "capital": "Banjul",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República da Gâmbia",
  "comum_ptBr": "Gâmbia"
 },
 {
  "id": 155,
  "cca2": "CY",
  "cca3": "CYP",
  "nome_comum": "Cyprus",
  "populacao": 1207361,
  "area_km2": 9251,
  "capital": "Nicosia",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "República de Chipre",
  "comum_ptBr": "Chipre"
 },
 {
  "id": 156,
  "cca2": "BQ",
  "cca3": "BES",
  "nome_comum": "Caribbean Netherlands",
  "populacao": 25987,
  "area_km2": 328,
  "capital": "Kralendijk",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Bonaire, Saba e Santo Eustáquio",
  "comum_ptBr": "Países Baixos Caribenhos"
 },
 {
  "id": 157,
  "cca2": "VU",
  "cca3": "VUT",
  "nome_comum": "Vanuatu",
  "populacao": 307150,
  "area_km2": 12189,
  "capital": "Port Vila",
  "regiao": "Oceania",
  "sub_regiao": "Melanesia",
  "oficial_ptBr": "República de Vanuatu",
  "comum_ptBr": "Vanuatu"
 },
 {
  "id": 158,
  "cca2": "PT",
  "cca3": "PRT",
  "nome_comum": "Portugal",
  "populacao": 10305564,
  "area_km2": 92090,
  "capital": "Lisbon",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "República português",
  "comum_ptBr": "Portugal"
 },
 {
  "id": 159,
  "cca2": "CN",
  "cca3": "CHN",
  "nome_comum": "China",
  "populacao": 1402112000,
  "area_km2": 9706961,
  "capital": "Beijing",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "República Popular da China",
  "comum_ptBr": "China"
 },
 {
  "id": 160,
  "cca2": "SG",
  "cca3": "SGP",
  "nome_comum": "Singapore",
  "populacao": 5685807,
  "area_km2": 710,
  "capital": "Singapore",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "República de Singapura",
  "comum_ptBr": "Singapura"
 },
 {
  "id": 161,
  "cca2": "DK",
  "cca3": "DNK",
  "nome_comum": "Denmark",
  "populacao": 5831404,
  "area_km2": 43094,
  "capital": "Copenhagen",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Reino da Dinamarca",
  "comum_ptBr": "Dinamarca"
 },
 {
  "id": 162,
  "cca2": "GH",
  "cca3": "GHA",
  "nome_comum": "Ghana",
  "populacao": 31072945,
  "area_km2": 238533,
  "capital": "Accra",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República do Gana",
  "comum_ptBr": "Gana"
 },
 {
  "id": 163,
  "cca2": "VC",
  "cca3": "VCT",
  "nome_comum": "Saint Vincent and the Grenadines",
  "populacao": 110947,
  "area_km2": 389,
  "capital": "Kingstown",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "São Vicente e Granadinas",
  "comum_ptBr": "São Vincente e Granadinas"
 },
 {
  "id": 164,
  "cca2": "MF",
  "cca3": "MAF",
  "nome_comum": "Saint Martin",
  "populacao": 38659,
  "area_km2": 53,
  "capital": "Marigot",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "saint Martin",
  "comum_ptBr": "São Martinho"
 },
 {
  "id": 165,
  "cca2": "LR",
  "cca3": "LBR",
  "nome_comum": "Liberia",
  "populacao": 5057677,
  "area_km2": 111369,
  "capital": "Monrovia",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República da Libéria",
  "comum_ptBr": "Libéria"
 },
 {
  "id": 166,
  "cca2": "HK",
  "cca3": "HKG",
  "nome_comum": "Hong Kong",
  "populacao": 7500700,
  "area_km2": 1104,
  "capital": "City of Victoria",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "Hong Kong Região Administrativa Especial da República Popular da China",
  "comum_ptBr": "Hong Kong"
 },
 {
  "id": 167,
  "cca2": "GT",
  "cca3": "GTM",
  "nome_comum": "Guatemala",
  "populacao": 16858333,
  "area_km2": 108889,
  "capital": "Guatemala City",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "República da Guatemala",
  "comum_ptBr": "Guatemala"
 },
 {
  "id": 168,
  "cca2": "SL",
  "cca3": "SLE",
  "nome_comum": "Sierra Leone",
  "populacao": 7976985,
  "area_km2": 71740,
  "capital": "Freetown",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República da Serra Leoa",
  "comum_ptBr": "Serra Leoa"
 },
 {
  "id": 169,
  "cca2": "MC",
  "cca3": "MCO",
  "nome_comum": "Monaco",
  "populacao": 39244,
  "area_km2": 2.02,
  "capital": "Monaco",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "Principado do Mónaco",
  "comum_ptBr": "Mónaco"
 },
 {
  "id": 170,
  "cca2": "LB",
  "cca3": "LBN",
  "nome_comum": "Lebanon",
  "populacao": 6825442,
  "area_km2": 10452,
  "capital": "Beirut",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República Libanesa",
  "comum_ptBr": "Líbano"
 },
 {
  "id": 171,
  "cca2": "SC",
  "cca3": "SYC",
  "nome_comum": "Seychelles",
  "populacao": 98462,
  "area_km2": 452,
  "capital": "Victoria",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República das Seychelles",
  "comum_ptBr": "Seicheles"
 },
 {
  "id": 172,
  "cca2": "ZM",
  "cca3": "ZMB",
  "nome_comum": "Zambia",
  "populacao": 18383956,
  "area_km2": 752612,
  "capital": "Lusaka",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República da Zâmbia",
  "comum_ptBr": "Zâmbia"
 },
 {
  "id": 173,
  "cca2": "VE",
  "cca3": "VEN",
  "nome_comum": "Venezuela",
  "populacao": 28435943,
  "area_km2": 916445,
  "capital": "Caracas",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República Bolivariana da Venezuela",
  "comum_ptBr": "Venezuela"
 },
 {
  "id": 174,
  "cca2": "SR",
  "cca3": "SUR",
  "nome_comum": "Suriname",
  "populacao": 586634,
  "area_km2": 163820,
  "capital": "Paramaribo",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República do Suriname",
  "comum_ptBr": "Suriname"
 },
 {
  "id": 175,
  "cca2": "RE",
  "cca3": "REU",
  "nome_comum": "Réunion",
  "populacao": 840974,
  "area_km2": 2511,
  "capital": "Saint-Denis",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "Ilha da Reunião",
  "comum_ptBr": "Reunião"
 },
 {
  "id": 176,
  "cca2": "UA",
  "cca3": "UKR",
  "nome_comum": "Ukraine",
  "populacao": 44134693,
  "area_km2": 603500,
  "capital": "Kyiv",
  "regiao": "Europe",
  "sub_regiao": "Eastern Europe",
  "oficial_ptBr": "Ucrânia",
  "comum_ptBr": "Ucrânia"
 },
 {
  "id": 177,
  "cca2": "LV",
  "cca3": "LVA",
  "nome_comum": "Latvia",
  "populacao": 1901548,
  "area_km2": 64559,
  "capital": "Riga",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "República da Letónia",
  "comum_ptBr": "Letónia"
 },
 {
  "id": 178,
  "cca2": "DE",
  "cca3": "DEU",
  "nome_comum": "Germany",
  "populacao": 83240525,
  "area_km2": 357114,
  "capital": "Berlin",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "República Federal da Alemanha",
  "comum_ptBr": "Alemanha"
 },
 {
  "id": 179,
  "cca2": "ER",
  "cca3": "ERI",
  "nome_comum": "Eritrea",
  "populacao": 5352000,
  "area_km2": 117600,
  "capital": "Asmara",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "Estado da Eritreia",
  "comum_ptBr": "Eritreia"
 },
 {
  "id": 180,
  "cca2": "HR",
  "cca3": "HRV",
  "nome_comum": "Croatia",
  "populacao": 4047200,
  "area_km2": 56594,
  "capital": "Zagreb",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "República da Croácia",
  "comum_ptBr": "Croácia"
 },
 {
  "id": 181,
  "cca2": "PG",
  "cca3": "PNG",
  "nome_comum": "Papua New Guinea",
  "populacao": 8947027,
  "area_km2": 462840,
  "capital": "Port Moresby",
  "regiao": "Oceania",
  "sub_regiao": "Melanesia",
  "oficial_ptBr": "Estado Independente da Papua Nova Guiné",
  "comum_ptBr": "Papua Nova Guiné"
 },
 {
  "id": 182,
  "cca2": "PW",
  "cca3": "PLW",
  "nome_comum": "Palau",
  "populacao": 18092,
  "area_km2": 459,
  "capital": "Ngerulmud",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "República de Palau",
  "comum_ptBr": "Palau"
 },
 {
  "id": 183,
  "cca2": "BA",
  "cca3": "BIH",
  "nome_comum": "Bosnia and Herzegovina",
  "populacao": 3280815,
  "area_km2": 51209,
  "capital": "Sarajevo",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "Bósnia e Herzegovina",
  "comum_ptBr": "Bósnia e Herzegovina"
 },
 {
  "id": 184,
  "cca2": "ME",
  "cca3": "MNE",
  "nome_comum": "Montenegro",
  "populacao": 621718,
  "area_km2": 13812,
  "capital": "Podgorica",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "Montenegro",
  "comum_ptBr": "Montenegro"
 },
 {
  "id": 185,
  "cca2": "LY",
  "cca3": "LBY",
  "nome_comum": "Libya",
  "populacao": 6871287,
  "area_km2": 1759540,
  "capital": "Tripoli",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "Estado da Líbia",
  "comum_ptBr": "Líbia"
 },
 {
  "id": 186,
  "cca2": "QA",
  "cca3": "QAT",
  "nome_comum": "Qatar",
  "populacao": 2881060,
  "area_km2": 11586,
  "capital": "Doha",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Estado do Qatar",
  "comum_ptBr": "Catar"
 },
 {
  "id": 187,
  "cca2": "PK",
  "cca3": "PAK",
  "nome_comum": "Pakistan",
  "populacao": 220892331,
  "area_km2": 881912,
  "capital": "Islamabad",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República Islâmica do Paquistão",
  "comum_ptBr": "Paquistão"
 },
 {
  "id": 188,
  "cca2": "KP",
  "cca3": "PRK",
  "nome_comum": "North Korea",
  "populacao": 25778815,
  "area_km2": 120538,
  "capital": "Pyongyang",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "República Popular Democrática da Coreia",
  "comum_ptBr": "Coreia do Norte"
 },
 {
  "id": 189,
  "cca2": "SM",
  "cca3": "SMR",
  "nome_comum": "San Marino",
  "populacao": 33938,
  "area_km2": 61,
  "capital": "City of San Marino",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "Sereníssima República de San Marino",
  "comum_ptBr": "San Marino"
 },
 {
  "id": 190,
  "cca2": "GN",
  "cca3": "GIN",
  "nome_comum": "Guinea",
  "populacao": 13132792,
  "area_km2": 245857,
  "capital": "Conakry",
  "regiao": "Africa",
  "sub_regiao": "Western Africa",
  "oficial_ptBr": "República da Guiné",
  "comum_ptBr": "Guiné"
 },
 {
  "id": 191,
  "cca2": "AI",
  "cca3": "AIA",
  "nome_comum": "Anguilla",
  "populacao": 13452,
  "area_km2": 91,
  "capital": "The Valley",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Anguilla",
  "comum_ptBr": "Anguilla"
 },
 {
  "id": 192,
  "cca2": "BN",
  "cca3": "BRN",
  "nome_comum": "Brunei",
  "populacao": 437483,
  "area_km2": 5765,
  "capital": "Bandar Seri Begawan",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "Nação do Brunei, Morada da Paz",
  "comum_ptBr": "Brunei"
 },
 {
  "id": 193,
  "cca2": "MG",
  "cca3": "MDG",
  "nome_comum": "Madagascar",
  "populacao": 27691019,
  "area_km2": 587041,
  "capital": "Antananarivo",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República de Madagáscar",
  "comum_ptBr": "Madagáscar"
 },
 {
  "id": 194,
  "cca2": "AZ",
  "cca3": "AZE",
  "nome_comum": "Azerbaijan",
  "populacao": 10110116,
  "area_km2": 86600,
  "capital": "Baku",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República do Azerbaijão",
  "comum_ptBr": "Azerbeijão"
 },
 {
  "id": 195,
  "cca2": "PS",
  "cca3": "PSE",
  "nome_comum": "Palestine",
  "populacao": 4803269,
  "area_km2": 6220,
  "capital": "Ramallah",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Estado da Palestina",
  "comum_ptBr": "Palestina"
 },
 {
  "id": 196,
  "cca2": "CF",
  "cca3": "CAF",
  "nome_comum": "Central African Republic",
  "populacao": 4829764,
  "area_km2": 622984,
  "capital": "Bangui",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República Centro-Africano",
  "comum_ptBr": "República Centro-Africana"
 },
 {
  "id": 197,
  "cca2": "GD",
  "cca3": "GRD",
  "nome_comum": "Grenada",
  "populacao": 112519,
  "area_km2": 344,
  "capital": "St. George's",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Grenada",
  "comum_ptBr": "Granada"
 },
 {
  "id": 198,
  "cca2": "BH",
  "cca3": "BHR",
  "nome_comum": "Bahrain",
  "populacao": 1701583,
  "area_km2": 765,
  "capital": "Manama",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Reino do Bahrein",
  "comum_ptBr": "Bahrein"
 },
 {
  "id": 199,
  "cca2": "AT",
  "cca3": "AUT",
  "nome_comum": "Austria",
  "populacao": 8917205,
  "area_km2": 83871,
  "capital": "Vienna",
  "regiao": "Europe",
  "sub_regiao": "Central Europe",
  "oficial_ptBr": "República da Áustria",
  "comum_ptBr": "Áustria"
 },
 {
  "id": 200,
  "cca2": "FR",
  "cca3": "FRA",
  "nome_comum": "France",
  "populacao": 67391582,
  "area_km2": 551695,
  "capital": "Paris",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "República Francesa",
  "comum_ptBr": "França"
 },
 {
  "id": 201,
  "cca2": "GI",
  "cca3": "GIB",
  "nome_comum": "Gibraltar",
  "populacao": 33691,
  "area_km2": 6,
  "capital": "Gibraltar",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "Gibraltar",
  "comum_ptBr": "Gibraltar"
 },
 {
  "id": 202,
  "cca2": "SV",
  "cca3": "SLV",
  "nome_comum": "El Salvador",
  "populacao": 6486201,
  "area_km2": 21041,
  "capital": "San Salvador",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "República de El Salvador",
  "comum_ptBr": "El Salvador"
 },
 {
  "id": 203,
  "cca2": "MK",
  "cca3": "MKD",
  "nome_comum": "North Macedonia",
  "populacao": 2077132,
  "area_km2": 25713,
  "capital": "Skopje",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "República da Macedônia do Norte",
  "comum_ptBr": "Macedónia do Norte"
 },
 {
  "id": 204,
  "cca2": "GF",
  "cca3": "GUF",
  "nome_comum": "French Guiana",
  "populacao": 254541,
  "area_km2": 83534,
  "capital": "Cayenne",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "Guiana",
  "comum_ptBr": "Guiana Francesa"
 },
 {
  "id": 205,
  "cca2": "NA",
  "cca3": "NAM",
  "nome_comum": "Namibia",
  "populacao": 2540916,
  "area_km2": 825615,
  "capital": "Windhoek",
  "regiao": "Africa",
  "sub_regiao": "Southern Africa",
  "oficial_ptBr": "República da Namíbia",
  "comum_ptBr": "Namíbia"
 },
 {
  "id": 206,
  "cca2": "AU",
  "cca3": "AUS",
  "nome_comum": "Australia",
  "populacao": 25687041,
  "area_km2": 7692024,
  "capital": "Canberra",
  "regiao": "Oceania",
  "sub_regiao": "Australia and New Zealand",
  "oficial_ptBr": "Comunidade da Austrália",
  "comum_ptBr": "Austrália"
 },
 {
  "id": 207,
  "cca2": "MA",
  "cca3": "MAR",
  "nome_comum": "Morocco",
  "populacao": 36910558,
  "area_km2": 446550,
  "capital": "Rabat",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "Reino de Marrocos",
  "comum_ptBr": "Marrocos"
 },
 {
  "id": 208,
  "cca2": "IE",
  "cca3": "IRL",
  "nome_comum": "Ireland",
  "populacao": 4994724,
  "area_km2": 70273,
  "capital": "Dublin",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "República da Irlanda",
  "comum_ptBr": "Irlanda"
 },
 {
  "id": 209,
  "cca2": "BM",
  "cca3": "BMU",
  "nome_comum": "Bermuda",
  "populacao": 63903,
  "area_km2": 54,
  "capital": "Hamilton",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Bermudas",
  "comum_ptBr": "Bermudas"
 },
 {
  "id": 210,
  "cca2": "NI",
  "cca3": "NIC",
  "nome_comum": "Nicaragua",
  "populacao": 6624554,
  "area_km2": 130373,
  "capital": "Managua",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "República da Nicarágua",
  "comum_ptBr": "Nicarágua"
 },
 {
  "id": 211,
  "cca2": "AX",
  "cca3": "ALA",
  "nome_comum": "Åland Islands",
  "populacao": 29458,
  "area_km2": 1580,
  "capital": "Mariehamn",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Ilhas Åland",
  "comum_ptBr": "Alândia"
 },
 {
  "id": 212,
  "cca2": "BS",
  "cca3": "BHS",
  "nome_comum": "Bahamas",
  "populacao": 393248,
  "area_km2": 13943,
  "capital": "Nassau",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Comunidade das Bahamas",
  "comum_ptBr": "Bahamas"
 },
 {
  "id": 213,
  "cca2": "OM",
  "cca3": "OMN",
  "nome_comum": "Oman",
  "populacao": 5106622,
  "area_km2": 309500,
  "capital": "Muscat",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Sultanato de Omã",
  "comum_ptBr": "Omã"
 },
 {
  "id": 214,
  "cca2": "CH",
  "cca3": "CHE",
  "nome_comum": "Switzerland",
  "populacao": 8654622,
  "area_km2": 41284,
  "capital": "Bern",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "Confederação Suíça",
  "comum_ptBr": "Suíça"
 },
 {
  "id": 215,
  "cca2": "CZ",
  "cca3": "CZE",
  "nome_comum": "Czechia",
  "populacao": 10698896,
  "area_km2": 78865,
  "capital": "Prague",
  "regiao": "Europe",
  "sub_regiao": "Central Europe",
  "oficial_ptBr": "República Checa",
  "comum_ptBr": "Chéquia"
 },
 {
  "id": 216,
  "cca2": "IS",
  "cca3": "ISL",
  "nome_comum": "Iceland",
  "populacao": 366425,
  "area_km2": 103000,
  "capital": "Reykjavik",
  "regiao": "Europe",
  "sub_regiao": "Northern Europe",
  "oficial_ptBr": "Islândia",
  "comum_ptBr": "Islândia"
 },
 {
  "id": 217,
  "cca2": "JP",
  "cca3": "JPN",
  "nome_comum": "Japan",
  "populacao": 125836021,
  "area_km2": 377930,
  "capital": "Tokyo",
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "Japão",
  "comum_ptBr": "Japão"
 },
 {
  "id": 218,
  "cca2": "NL",
  "cca3": "NLD",
  "nome_comum": "Netherlands",
  "populacao": 16655799,
  "area_km2": 41850,
  "capital": "Amsterdam",
  "regiao": "Europe",
  "sub_regiao": "Western Europe",
  "oficial_ptBr": "Holanda",
  "comum_ptBr": "Holanda"
 },
 {
  "id": 219,
  "cca2": "BZ",
  "cca3": "BLZ",
  "nome_comum": "Belize",
  "populacao": 397621,
  "area_km2": 22966,
  "capital": "Belmopan",
  "regiao": "Americas",
  "sub_regiao": "Central America",
  "oficial_ptBr": "Belize",
  "comum_ptBr": "Belize"
 },
 {
  "id": 220,
  "cca2": "BB",
  "cca3": "BRB",
  "nome_comum": "Barbados",
  "populacao": 287371,
  "area_km2": 430,
  "capital": "Bridgetown",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Barbados",
  "comum_ptBr": "Barbados"
 },
 {
  "id": 221,
  "cca2": "BY",
  "cca3": "BLR",
  "nome_comum": "Belarus",
  "populacao": 9398861,
  "area_km2": 207600,
  "capital": "Minsk",
  "regiao": "Europe",
  "sub_regiao": "Eastern Europe",
  "oficial_ptBr": "República da Bielorrússia",
  "comum_ptBr": "Bielorússia"
 },
 {
  "id": 222,
  "cca2": "TL",
  "cca3": "TLS",
  "nome_comum": "Timor-Leste",
  "populacao": 1318442,
  "area_km2": 14874,
  "capital": "Dili",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "República Democrática de Timor-Leste",
  "comum_ptBr": "Timor-Leste"
 },
 {
  "id": 223,
  "cca2": "UG",
  "cca3": "UGA",
  "nome_comum": "Uganda",
  "populacao": 45741000,
  "area_km2": 241550,
  "capital": "Kampala",
  "regiao": "Africa",
  "sub_regiao": "Eastern Africa",
  "oficial_ptBr": "República do Uganda",
  "comum_ptBr": "Uganda"
 },
 {
  "id": 224,
  "cca2": "YE",
  "cca3": "YEM",
  "nome_comum": "Yemen",
  "populacao": 29825968,
  "area_km2": 527968,
  "capital": "Sana'a",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "República do Iêmen",
  "comum_ptBr": "Iémen"
 },
 {
  "id": 225,
  "cca2": "MQ",
  "cca3": "MTQ",
  "nome_comum": "Martinique",
  "populacao": 378243,
  "area_km2": 1128,
  "capital": "Fort-de-France",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Martinique",
  "comum_ptBr": "Martinica"
 },
 {
  "id": 226,
  "cca2": "HT",
  "cca3": "HTI",
  "nome_comum": "Haiti",
  "populacao": 11402533,
  "area_km2": 27750,
  "capital": "Port-au-Prince",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "República do Haiti",
  "comum_ptBr": "Haiti"
 },
 {
  "id": 227,
  "cca2": "AR",
  "cca3": "ARG",
  "nome_comum": "Argentina",
  "populacao": 45376763,
  "area_km2": 2780400,
  "capital": "Buenos Aires",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República Argentina",
  "comum_ptBr": "Argentina"
 },
 {
  "id": 228,
  "cca2": "EG",
  "cca3": "EGY",
  "nome_comum": "Egypt",
  "populacao": 102334403,
  "area_km2": 1002450,
  "capital": "Cairo",
  "regiao": "Africa",
  "sub_regiao": "Northern Africa",
  "oficial_ptBr": "República Árabe do Egipto",
  "comum_ptBr": "Egito"
 },
 {
  "id": 229,
  "cca2": "KW",
  "cca3": "KWT",
  "nome_comum": "Kuwait",
  "populacao": 4270563,
  "area_km2": 17818,
  "capital": "Kuwait City",
  "regiao": "Asia",
  "sub_regiao": "Western Asia",
  "oficial_ptBr": "Estado do Kuwait",
  "comum_ptBr": "Kuwait"
 },
 {
  "id": 230,
  "cca2": "KY",
  "cca3": "CYM",
  "nome_comum": "Cayman Islands",
  "populacao": 65720,
  "area_km2": 264,
  "capital": "George Town",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Ilhas Cayman",
  "comum_ptBr": "Ilhas Caimão"
 },
 {
  "id": 231,
  "cca2": "CK",
  "cca3": "COK",
  "nome_comum": "Cook Islands",
  "populacao": 18100,
  "area_km2": 236,
  "capital": "Avarua",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Ilhas Cook",
  "comum_ptBr": "Ilhas Cook"
 },
 {
  "id": 232,
  "cca2": "AQ",
  "cca3": "ATA",
  "nome_comum": "Antarctica",
  "populacao": 1000,
  "area_km2": 14000000,
  "regiao": "Antarctic",
  "sub_regiao": "",
  "oficial_ptBr": "Antártica",
  "comum_ptBr": "Antártida"
 },
 {
  "id": 233,
  "cca2": "GA",
  "cca3": "GAB",
  "nome_comum": "Gabon",
  "populacao": 2225728,
  "area_km2": 267668,
  "capital": "Libreville",
  "regiao": "Africa",
  "sub_regiao": "Middle Africa",
  "oficial_ptBr": "República do Gabão",
  "comum_ptBr": "Gabão"
 },
 {
  "id": 234,
  "cca2": "LK",
  "cca3": "LKA",
  "nome_comum": "Sri Lanka",
  "populacao": 21919000,
  "area_km2": 65610,
  "capital": "Sri Jayawardenepura Kotte",
  "regiao": "Asia",
  "sub_regiao": "Southern Asia",
  "oficial_ptBr": "República Democrática Socialista do Sri Lanka",
  "comum_ptBr": "Sri Lanka"
 },
 {
  "id": 235,
  "cca2": "TT",
  "cca3": "TTO",
  "nome_comum": "Trinidad and Tobago",
  "populacao": 1399491,
  "area_km2": 5130,
  "capital": "Port of Spain",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "República de Trinidad e Tobago",
  "comum_ptBr": "Trinidade e Tobago"
 },
 {
  "id": 236,
  "cca2": "CO",
  "cca3": "COL",
  "nome_comum": "Colombia",
  "populacao": 50882884,
  "area_km2": 1141748,
  "capital": "Bogotá",
  "regiao": "Americas",
  "sub_regiao": "South America",
  "oficial_ptBr": "República da Colômbia",
  "comum_ptBr": "Colômbia"
 },
 {
  "id": 237,
  "cca2": "VA",
  "cca3": "VAT",
  "nome_comum": "Vatican City",
  "populacao": 451,
  "area_km2": 0.44,
  "capital": "Vatican City",
  "regiao": "Europe",
  "sub_regiao": "Southern Europe",
  "oficial_ptBr": "Cidade do Vaticano",
  "comum_ptBr": "Cidade do Vaticano"
 },
 {
  "id": 238,
  "cca2": "CX",
  "cca3": "CXR",
  "nome_comum": "Christmas Island",
  "populacao": 2072,
  "area_km2": 135,
  "capital": "Flying Fish Cove",
  "regiao": "Oceania",
  "sub_regiao": "Australia and New Zealand",
  "oficial_ptBr": "Território da Ilha Christmas",
  "comum_ptBr": "Ilha do Natal"
 },
 {
  "id": 239,
  "cca2": "HM",
  "cca3": "HMD",
  "nome_comum": "Heard Island and McDonald Islands",
  "populacao": 0,
  "area_km2": 412,
  "regiao": "Antarctic",
  "sub_regiao": "",
  "oficial_ptBr": "Ilha Heard e Ilhas McDonald",
  "comum_ptBr": "Ilha Heard e Ilhas McDonald"
 },
 {
  "id": 240,
  "cca2": "MO",
  "cca3": "MAC",
  "nome_comum": "Macau",
  "populacao": 649342,
  "area_km2": 30,
  "regiao": "Asia",
  "sub_regiao": "Eastern Asia",
  "oficial_ptBr": "Macau Região Administrativa Especial da República Popular da China",
  "comum_ptBr": "Macau"
 },
 {
  "id": 241,
  "cca2": "MX",
  "cca3": "MEX",
  "nome_comum": "Mexico",
  "populacao": 128932753,
  "area_km2": 1964375,
  "capital": "Mexico City",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Estados Unidos Mexicanos",
  "comum_ptBr": "México"
 },
 {
  "id": 242,
  "cca2": "NC",
  "cca3": "NCL",
  "nome_comum": "New Caledonia",
  "populacao": 271960,
  "area_km2": 18575,
  "capital": "Nouméa",
  "regiao": "Oceania",
  "sub_regiao": "Melanesia",
  "oficial_ptBr": "New Caledonia",
  "comum_ptBr": "Nova Caledónia"
 },
 {
  "id": 243,
  "cca2": "SB",
  "cca3": "SLB",
  "nome_comum": "Solomon Islands",
  "populacao": 686878,
  "area_km2": 28896,
  "capital": "Honiara",
  "regiao": "Oceania",
  "sub_regiao": "Melanesia",
  "oficial_ptBr": "Ilhas Salomão",
  "comum_ptBr": "Ilhas Salomão"
 },
 {
  "id": 244,
  "cca2": "XK",
  "cca3": "UNK",
  "nome_comum": "Kosovo",
  "populacao": 1775378,
  "area_km2": 10908,
  "capital": "Pristina",
  "regiao": "Europe",
  "sub_regiao": "Southeast Europe",
  "oficial_ptBr": "República do Kosovo",
  "comum_ptBr": "Kosovo"
 },
 {
  "id": 245,
  "cca2": "NR",
  "cca3": "NRU",
  "nome_comum": "Nauru",
  "populacao": 10834,
  "area_km2": 21,
  "capital": "Yaren",
  "regiao": "Oceania",
  "sub_regiao": "Micronesia",
  "oficial_ptBr": "República de Nauru",
  "comum_ptBr": "Nauru"
 },
 {
  "id": 246,
  "cca2": "TO",
  "cca3": "TON",
  "nome_comum": "Tonga",
  "populacao": 105697,
  "area_km2": 747,
  "capital": "Nuku'alofa",
  "regiao": "Oceania",
  "sub_regiao": "Polynesia",
  "oficial_ptBr": "Reino de Tonga",
  "comum_ptBr": "Tonga"
 },
 {
  "id": 247,
  "cca2": "MY",
  "cca3": "MYS",
  "nome_comum": "Malaysia",
  "populacao": 32365998,
  "area_km2": 330803,
  "capital": "Kuala Lumpur",
  "regiao": "Asia",
  "sub_regiao": "South-Eastern Asia",
  "oficial_ptBr": "Malásia",
  "comum_ptBr": "Malásia"
 },
 {
  "id": 248,
  "cca2": "FJ",
  "cca3": "FJI",
  "nome_comum": "Fiji",
  "populacao": 896444,
  "area_km2": 18272,
  "capital": "Suva",
  "regiao": "Oceania",
  "sub_regiao": "Melanesia",
  "oficial_ptBr": "República de Fiji",
  "comum_ptBr": "Fiji"
 },
 {
  "id": 249,
  "cca2": "JM",
  "cca3": "JAM",
  "nome_comum": "Jamaica",
  "populacao": 2961161,
  "area_km2": 10991,
  "capital": "Kingston",
  "regiao": "Americas",
  "sub_regiao": "Caribbean",
  "oficial_ptBr": "Jamaica",
  "comum_ptBr": "Jamaica"
 },
 {
  "id": 250,
  "cca2": "UM",
  "cca3": "UMI",
  "nome_comum": "United States Minor Outlying Islands",
  "populacao": 300,
  "area_km2": 34.2,
  "capital": "Washington DC",
  "regiao": "Americas",
  "sub_regiao": "North America",
  "oficial_ptBr": "Estados Unidos Ilhas Menores Distantes",
  "comum_ptBr": "Ilhas Menores Distantes dos Estados Unidos"
 }
]




